name: Build on Windows and run Tests

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Adjust based on your target framework version
        
    # Install .NET MAUI
    - name: Install MAUI workload
      run: dotnet workload install maui

    # Install dependencies
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ./CryptoPulse

    # Build the project
    - name: Build Project
      run: dotnet build -c Release -f:net9.0

    # Run unit tests
    - name: Run Unit Tests
      run: dotnet test -c Release -f:net9.0
